### ISSUE TITLE
Suggested update for ability to set random seed for reproducibility

### ISSUE THREAD

**Issue by MatthewJMorris** [auggiemarignier/neighpy#5]
Hi,

Is it currently possible to set a random seed such that running the Search phase of the Neighbourhood Algorithm multiple times with the same data and objective function will produce identical results?

If not, this may be a useful functionality for reproducibility of results between different users.

Thanks

**Comment by auggiemarignier** [comment]
Thanks for the suggestion @MatthewJMorris! This is now possible in `v0.1.5`

**Comment by auggiemarignier** [comment]
@MatthewJMorris have you noticed #7 occurring in the searcher?

**Comment by MatthewJMorris** [comment]
@auggiemarignier I have been observing cases in the search phase where all search samples are identical between different runs when the seed is the same. In my view I think this is expected behaviour, even when the objective function changes slightly? Does this describe the same behaviour as #7 to you?

**Comment by auggiemarignier** [comment]
Yeah that's the expected behaviour.  What #7 is about is within the same run, two walkers produce the same chain of samples so the samples at the end are not properly distributed according to the posterior.  I haven't seen it happen in the searcher but I've applied the same fix just in case, which will come out soon

**Comment by MatthewJMorris** [comment]
Ah got it, thanks. No I haven't observed this in the searcher. Both the initial sampling and the resampling of cells seem to produce sensible distributions of samples.
